'use strict';

var { NativeModules, Platform } = require('react-native');

// AM5ProfileModule is iOS-only
var RCTModule = Platform.OS === 'ios' ? (NativeModules.AM5ProfileModule || {}) : {};

module.exports = {
  ACTION_ERROR: RCTModule.ACTION_ERROR,
  ERROR_NUM: RCTModule.ERROR_NUM,
  ERROR_DESCRIPTION: RCTModule.ERROR_DESCRIPTION,

  ACTION_USER_BIND: RCTModule.ACTION_USER_BIND,
  ACTION_USER_UNBIND: RCTModule.ACTION_USER_UNBIND,
  ACTION_FUNCTION_SUPPORT: RCTModule.ACTION_FUNCTION_SUPPORT,

  ACTION_BASIC_INFO: RCTModule.ACTION_BASIC_INFO,
  BASIC_BATTSTATUS: RCTModule.BASIC_BATTSTATUS,
  BASIC_DEIVCEID: RCTModule.BASIC_DEIVCEID,
  BASIC_ENERGE: RCTModule.BASIC_ENERGE,
  BASIC_FIRMWAREVERSION: RCTModule.BASIC_FIRMWAREVERSION,
  BASIC_MODE: RCTModule.BASIC_MODE,
  BASIC_PAIRFLAG: RCTModule.BASIC_PAIRFLAG,
  BASIC_REBOOT: RCTModule.BASIC_REBOOT,

  ACTION_LIVE_DATA: RCTModule.ACTION_LIVE_DATA,
  LIVE_DATA_HEARTRATE: RCTModule.LIVE_DATA_HEARTRATE,
  LIVE_DATA_STEP: RCTModule.LIVE_DATA_STEP,
  LIVE_DATA_DISTANCES: RCTModule.LIVE_DATA_DISTANCES,
  LIVE_DATA_ACTIVETIME: RCTModule.LIVE_DATA_ACTIVETIME,
  LIVE_DATA_CALORIE: RCTModule.LIVE_DATA_CALORIE,

  ACTION_ACTIVITY_COUNT: RCTModule.ACTION_ACTIVITY_COUNT,
  ACTION_SET_TIME: RCTModule.ACTION_SET_TIME,
  ACTION_SET_USER_INFO: RCTModule.ACTION_SET_USER_INFO,
  ACTION_SET_UNIT: RCTModule.ACTION_SET_UNIT,
  ACTION_SET_HAND_WEAR_MODE: RCTModule.ACTION_SET_HAND_WEAR_MODE,

  ACTION_SYNC_HEALTH_DATA: RCTModule.ACTION_SYNC_HEALTH_DATA,
  ACTION_SYNC_HEALTH_DATA_SPORT: RCTModule.ACTION_SYNC_HEALTH_DATA_SPORT,
  ACTION_SYNC_HEALTH_DATA_SLEEP: RCTModule.ACTION_SYNC_HEALTH_DATA_SLEEP,
  ACTION_SYNC_HEALTH_DATA_HEART_RATE: RCTModule.ACTION_SYNC_HEALTH_DATA_HEART_RATE,

  OPERATION_STATUS: RCTModule.OPERATION_STATUS,
  TYPE: RCTModule.TYPE,
  DATA: RCTModule.DATA,
  PROGRESS: RCTModule.PROGRESS,
  RESULT: RCTModule.RESULT,

  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES,
};
