'use strict';

var { NativeModules, Platform } = require('react-native');

// ECGProfileModule is iOS-only
var RCTModule = Platform.OS === 'ios' ? (NativeModules.ECGProfileModule || {}) : {};

module.exports = {
  ACTION_GET_ALL_CONNECTED_DEVICES: RCTModule.ACTION_GET_ALL_CONNECTED_DEVICES,
  DEVICES: RCTModule.DEVICES,

  // ECG3 - Error
  ACTION_ERROR_ECG: RCTModule.ACTION_ERROR_ECG,
  ERROR_NUM_ECG: RCTModule.ERROR_NUM_ECG,
  ERROR_DESCRIPTION_ECG: RCTModule.ERROR_DESCRIPTION_ECG,

  // ECG3 - Battery
  ACTION_BATTERY_ECG: RCTModule.ACTION_BATTERY_ECG,
  BATTERY_ECG: RCTModule.BATTERY_ECG,

  // ECG3 - Measurement
  ACTION_SYSTIME: RCTModule.ACTION_SYSTIME,
  ACTION_MEASURE_WAVEData: RCTModule.ACTION_MEASURE_WAVEData,
  ACTION_MEASURE_ECGPulse: RCTModule.ACTION_MEASURE_ECGPulse,
  MEASURE_WAVEData: RCTModule.MEASURE_WAVEData,
  MEASURE_ECGPulse: RCTModule.MEASURE_ECGPulse,
  ACTION_STOPMEASURE_ECG: RCTModule.ACTION_STOPMEASURE_ECG,
  ACTION_ELECTRODE_STATUS: RCTModule.ACTION_ELECTRODE_STATUS,
  ELECTRODE_STATUS: RCTModule.ELECTRODE_STATUS,

  // ECGUSB - Error
  ACTION_ERROR_ECGUSB: RCTModule.ACTION_ERROR_ECGUSB,
  ERROR_DESCRIPTION_ECGUSB: RCTModule.ERROR_DESCRIPTION_ECGUSB,
  ERROR_NUM_ECGUSB: RCTModule.ERROR_NUM_ECGUSB,

  // ECGUSB - Sync
  ACTION_SYNCDATA_ECGUSB: RCTModule.ACTION_SYNCDATA_ECGUSB,
  ACTION_STARTSYNCDATA_ECGUSB: RCTModule.ACTION_STARTSYNCDATA_ECGUSB,
  ACTION_SYNCDATAINFO_ECGUSB: RCTModule.ACTION_SYNCDATAINFO_ECGUSB,
  DATAINFO: RCTModule.DATAINFO,
  ACTION_FINISHSYNCDATA_ECGUSB: RCTModule.ACTION_FINISHSYNCDATA_ECGUSB,
  ACTION_SYNCDATAPROGRESS_ECGUSB: RCTModule.ACTION_SYNCDATAPROGRESS_ECGUSB,
  PROGRESS: RCTModule.PROGRESS,

  // ECGUSB - Other
  ACTION_DELETEDATA_ECGUSB: RCTModule.ACTION_DELETEDATA_ECGUSB,
  ACTION_SPLICE: RCTModule.ACTION_SPLICE,
  SPLICE_DATA: RCTModule.SPLICE_DATA,
  SPLICE_ERROR_DESCRIPTION: RCTModule.SPLICE_ERROR_DESCRIPTION,
  ACTION_GET_CACHE: RCTModule.ACTION_GET_CACHE,
  GET_CACHE_DATA: RCTModule.GET_CACHE_DATA,
  ACTION_FILTER: RCTModule.ACTION_FILTER,
  FILTER_DATA: RCTModule.FILTER_DATA,
  FILTER_ERROR_DESCRIPTION: RCTModule.FILTER_ERROR_DESCRIPTION,
};
